---
kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.4.1
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/rancher-webhook"
      tag: "${DRONE_TAG}-amd64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: arm64
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.4.1
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-arm64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/rancher-webhook"
      tag: "${DRONE_TAG}-arm64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: s390x
type: docker

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
  - name: build
    image: rancher/dapper:v0.5.8
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: github_binary_release
    image: rancher/drone-images:github-release-s390x
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-s390x.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish
    image: rancher/drone-images:docker-s390x
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/rancher-webhook"
      tag: "${DRONE_TAG}-s390x"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: manifest
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest
    image: plugins/manifest:1.0.2
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/s390x
      target: "rancher/rancher-webhook:${DRONE_TAG}"
      template: "rancher/rancher-webhook:${DRONE_TAG}-ARCH"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

depends_on:
  - amd64
  - arm64
  - s390x

---
kind: pipeline
name: fossa
type: docker

steps:
  - name: fossa
    image: rancher/drone-fossa:latest
    failure: ignore
    settings:
      api_key:
        from_secret: FOSSA_API_KEY
      when:
        instance:
          - drone-publish.rancher.io

---
kind: pipeline
type: docker
name: integration-test

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: registry.suse.com/bci/golang:1.19
    commands:
      # Needed to build webhook and test since the /drone/src repo is mounted and the files have different ownership
      - git config --global --add safe.directory /drone/src
      - go build -v -o ./webhook
      - go test ./tests/integration/... -c -o ./webhook-integration.test

  - name: test
    image: rancher/rancher:v2.7.0-rc4
    privileged: true
    commands:
      - scripts/integration-test
